version: '3'
services:
  gb-nginx:
    build: ./nginx
    container_name: gb-nginx
    volumes:
      - ./logs/nginx/:/var/log/nginx/
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
    #NOTE : TLS key's path for HTTPS
    # - <host ssl_certificate key's path> : <nginx.conf ssl_certificate key's path>
    # - <host ssl_certificate_key key's path> : <nginx.conf  ssl_certificate_key key's path>
    networks:
      - app_net
    hostname: nginx
    ports:
      - "8080:8080"
      - "29418:29418"
    depends_on:
      - gitbucket
    command: ["nginx", "-g", "daemon off;"]
    restart: unless-stopped
  gb-mysql:
    build: ./mysql
    container_name: gb-mysql
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE: gitbucket
      MYSQL_USER: gitbucket
      MYSQL_PASSWORD: gitbucket
    volumes:
      - ./storage/mysql/data:/var/lib/mysql
      - ./mysql/config/etc/conf.d/mysql_custom.cnf:/etc/mysql/conf.d/mysql_custom.cnf
    networks:
      - app_net
    hostname: gb-mysql
    expose:
      - "3306"
    command: ["mysqld"]
    restart: unless-stopped
  gitbucket:
    build: ./gitbucket
    container_name: gitbucket
    environment:
      MYSQL_USER: gitbucket
      MYSQL_PASSWORD: gitbucket
      MYSQL_URL: jdbc:mysql://gb-mysql:3306/gitbucket?useUnicode=true&characterEncoding=utf8
      LOGGING: 0
    networks:
      - app_net
    hostname: gitbucket
    expose:
      - "8080"
      - "29418"
    volumes:
     - ./storage/gitbucket/data:/gitbucket
     - ./logs/gitbucket/:/opt/gitbucket/log
    restart: unless-stopped
networks:
  app_net:
    driver: bridge
