version: '2'
services:
  gb-nginx:
    build: ./nginx
    container_name: gb-nginx
    volumes:
      - ./logs/nginx/:/var/log/nginx/
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
    #NOTE : TLS key's path for HTTPS
    # - <host ssl_certificate key's path> : <nginx.conf ssl_certificate key's path>
    # - <host ssl_certificate_key key's path> : <nginx.conf  ssl_certificate_key key's path>
    networks:
      - app_net
    hostname: nginx
    ports:
      - "8080:8080"
    depends_on:
      - gitbucket
    command: ["nginx", "-g", "daemon off;"]
  gb-mysql:
    build: ./mysql
    container_name: gb-mysql
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE: gitbucket      
      MYSQL_USER: gitbucket
      MYSQL_PASSWORD: gitbucket
    volumes_from:
      - gb-mysql-storage
    volumes:
      - /var/lib/mysql
    networks:
      - app_net
    hostname: gb-mysql
    expose:
      - "3306"
    command: ["mysqld"]
  gb-mysql-storage:
    build: ./storage/mysql
    container_name: gb-mysql-storage
    volumes:
     - ./storage/mysql/data:/var/lib/mysql    
  gitbucket:
    build: ./gitbucket
    container_name: gitbucket
    environment:
      MYSQL_USER: gitbucket
      MYSQL_PASSWORD: gitbucket
      MYSQL_URL: jdbc:mysql://gb-mysql:3306/gitbucket?useUnicode=true&characterEncoding=utf8
    networks:
      - app_net
    hostname: gitbucket
    expose:
      - "8080"
      - "29418"
    depends_on:
      - gitbucket-storage
    volumes_from:
      - gitbucket-storage
  gitbucket-storage:
    build: ./storage/gitbucket
    container_name: gitbucket-storage
    volumes:
     - ./storage/gitbucket/data:/gitbucket  
networks:
  app_net:
    driver: bridge