version: '2'
services:
  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - ./logs/nginx/:/var/log/nginx/
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
    #NOTE : TLS key's path for HTTPS
    # - <host ssl_certificate key's path> : <nginx.conf ssl_certificate key's path>
    # - <host ssl_certificate_key key's path> : <nginx.conf  ssl_certificate_key key's path>
    networks:
      - app_net
    hostname: nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - gitbucket
    depends_on:
      - gitbucket
    command: ["nginx", "-g", "daemon off;"]
  mariadb:
    build: ./mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_USER: gitbucket
      MYSQL_PASSWORD: gitbucket
      URL: jdbc:mysql://localhost/gitbucket?useUnicode=true&characterEncoding=utf8
    volumes_from:
      - mariadb-storage
    volumes:
      - /var/lib/mysql
      - ./mariadb/config/my.cnf:/etc/mysql/my.cnf
    networks:
      - app_net
    hostname: mariadb
    expose:
      - "3306"
    depends_on:
      - mariadb-storage
    command: mysqld
  gitbucket:
    build: ./gitbucket
    container_name: gitbucket
    environment:
      DB_PING_USER: gitbucket
      DB_PING_USER_PASSWORD: gitbucket
    networks:
      - app_net
    hostname: gitbucket
    expose:
      - "8080"
      - "29418"
    links:
      - mariadb
    depends_on:
      - mariadb
    volumes:
      - ./libexec/:/opt/
networks:
  app_net:
    driver: bridge